import path from 'node:path';
import { fileURLToPath } from 'node:url';
export const projectRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
export const dataDirectory=path.resolve(projectRoot,process.env.ADMIN_DATA_DIR??'data');
export const port=Number(process.env.ADMIN_PORT??4175);
export const uiPort=Number(process.env.ADMIN_UI_PORT??5175);
if(!Number.isInteger(port)||port<1024||port>65535||!Number.isInteger(uiPort)||uiPort<1024||uiPort>65535)throw new Error('Set valid ADMIN_PORT and ADMIN_UI_PORT values between 1024 and 65535.');
export const allowedOrigins=new Set([`http://localhost:${port}`,`http://127.0.0.1:${port}`,`http://localhost:${uiPort}`,`http://127.0.0.1:${uiPort}`]);
export const sessionCookie='ecec_local_admin';
export const sessionLifetime=8*60*60*1000;
