import {useState,type FormEvent} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {toast} from 'sonner';
async function api<T=unknown>(path:string,method='GET',body?:unknown):Promise<T>{const response=await fetch(path,{method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const result=await response.json();if(response.status===401)window.dispatchEvent(new Event('admin-session-expired'));if(!response.ok)throw new Error(result.error??'Could not complete the request.');return result;}
function CodeInput({value,onChange,id}:{value:string;onChange:(value:string)=>void;id:string}){return <div className="form-field"><label htmlFor={id}>Six-digit verification code</label><Input id={id} value={value} onChange={e=>onChange(e.target.value.replace(/[^0-9]/g,''))} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} required/></div>;}
export function ForgotPasswordForm({initialUsername,onDone}:{initialUsername:string;onDone:()=>void}){
 const [username,setUsername]=useState(initialUsername),[code,setCode]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[requested,setRequested]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function request(){setBusy(true);setError('');try{const result=await api<{message:string}>('/api/auth/reset/request','POST',{username});setRequested(true);setNotice(result.message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function submit(event:FormEvent){event.preventDefault();if(password!==confirm){setError('New passwords do not match.');return;}setBusy(true);setError('');try{await api('/api/auth/reset/confirm','POST',{username,code,newPassword:password});toast.success('Password reset. Sign in with your new password.');onDone();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className="password-change-form" onSubmit={submit}><div className="form-field"><label htmlFor="reset-username">Username</label><Input id="reset-username" required maxLength={120} value={username} readOnly={requested} onChange={e=>setUsername(e.target.value)}/></div><Button type="button" variant="outline" disabled={busy||!username.trim()} onClick={request}>{busy?'Please wait…':requested?'Send another code':'Email verification code'}</Button>{notice&&<p className="secondary-text" role="status">{notice}</p>}{requested&&<><CodeInput id="reset-code" value={code} onChange={setCode}/><div className="form-field"><label htmlFor="reset-password">New password</label><Input id="reset-password" type="password" autoComplete="new-password" required minLength={8} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></div><div className="form-field"><label htmlFor="reset-confirm">Confirm new password</label><Input id="reset-confirm" type="password" autoComplete="new-password" required minLength={8} maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)}/></div><Button type="submit" className="primary-button" disabled={busy}>Verify &amp; reset password</Button></>}{error&&<p className="form-error" role="alert">{error}</p>}</form>;
}
export function PasswordForm(){
 const [open,setOpen]=useState(false),[current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function clear(){setCurrent('');setNext('');setConfirm('');setCode('');setSent(false);setError('');}
 async function request(){setBusy(true);setError('');try{await api('/api/auth/password/code','POST',{currentPassword:current});setSent(true);toast.success('Verification code sent to your recovery email');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function submit(event:FormEvent){event.preventDefault();if(next!==confirm){setError('New passwords do not match.');return;}setBusy(true);setError('');try{await api('/api/auth/password','PATCH',{currentPassword:current,newPassword:next,code});setOpen(false);clear();toast.success('Password changed. Other sessions were signed out.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><Button className="password-change-button" variant="outline" onClick={()=>{clear();setOpen(true);}}>Change password</Button><Dialog open={open} onOpenChange={value=>{if(!busy){setOpen(value);if(!value)clear();}}}><DialogContent className="message-dialog"><DialogHeader><DialogTitle>Change admin password</DialogTitle><DialogDescription>Verify your recovery email to change your password. Codes expire after 10 minutes.</DialogDescription></DialogHeader><form className="password-change-form" onSubmit={submit}><div className="form-field"><label htmlFor="current-password">Current password</label><Input id="current-password" type="password" autoComplete="current-password" value={current} onChange={e=>{setCurrent(e.target.value);setSent(false);}} required maxLength={128}/></div><Button type="button" variant="outline" disabled={busy||!current} onClick={request}>{busy?'Please wait…':sent?'Send another code':'Email verification code'}</Button>{sent&&<CodeInput id="change-code" value={code} onChange={setCode}/>}<div className="form-field"><label htmlFor="new-password">New password</label><Input id="new-password" type="password" autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)} required minLength={8} maxLength={128}/></div><div className="form-field"><label htmlFor="confirm-new-password">Confirm new password</label><Input id="confirm-new-password" type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required minLength={8} maxLength={128}/></div>{error&&<p className="form-error" role="alert">{error}</p>}<Button type="submit" className="primary-button" disabled={busy||!sent}>{busy?'Saving…':'Verify & change password'}</Button></form></DialogContent></Dialog></>;
}
