'use client';
import {subscribeLive} from '../../shared/live';
import { useEffect,useMemo,useState,type FormEvent,type CSSProperties } from 'react';
import {PasswordForm} from './AccountForms';
import { Link,useRouter } from './navigation';
import { UserRound,LayoutGrid,ClipboardList,Users,Star,BookOpen,Images,CalendarDays,FileText,Settings as SettingsIcon,LogOut,Plus,Search,Pencil,Trash2,Check,RefreshCw,ShieldCheck,Clock,Inbox } from 'lucide-react';
import { SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar } from '@/components/ui/sidebar';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogFooter } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel } from '@/components/ui/alert-dialog';
import { Table,TableHeader,TableHead,TableBody,TableRow,TableCell } from '@/components/ui/table';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Toaster,toast } from 'sonner';
import { config,dateLabel,settingsSchema,validateRecord,isCategoryKind,categoryKinds,recordCategories,normalizeCategory,categoryNameSchema,type CategoryKind,type CategoryLists,type AdminRecord,type Kind,type PortalData,type Section,type Settings,type Field } from './admin-model';

const navigation=[
  {id:'overview',label:'Quick Actions',icon:LayoutGrid},{id:'admissions',label:'Admissions',icon:ClipboardList},{id:'staff',label:'Staff & Teachers',icon:Users},{id:'reviews',label:'Reviews',icon:Star},{id:'programs',label:'Programs',icon:BookOpen},{id:'gallery',label:'Gallery',icon:Images},{id:'events',label:'Events',icon:CalendarDays},{id:'blog',label:'Blog',icon:FileText},{id:'settings',label:'Settings',icon:SettingsIcon},
] as const;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Katmandu',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const timeLabel=(value:string)=>new Intl.DateTimeFormat('en',{hour:'numeric',minute:'2-digit',hour12:true,timeZone:'UTC'}).format(new Date(`2000-01-01T${value}:00Z`));
const titleCase=(text:string)=>text.charAt(0).toUpperCase()+text.slice(1);
async function requestJson<T=unknown>(url:string,method='GET',body?:unknown):Promise<T>{
  const response=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});
  let data:unknown;try{data=await response.json();}catch{throw new Error('Your session may have expired. Reload and sign in again.');}
  if(response.status===401)window.dispatchEvent(new Event('admin-session-expired'));
  if(!response.ok)throw new Error((data as {error?:string})?.error??'Could not save your changes.');
  return data as T;
}
function Status({value}:{value:string}){return <span className={`status status-${value.toLowerCase()}`}>{value}</span>;}
function StaffAvatar({record}:{record:AdminRecord}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[record.data.imagePath]);return <div className="staff-avatar">{record.data.imagePath&&!failed?<img src={record.data.imagePath} alt={record.name} loading="lazy" onError={()=>setFailed(true)}/>:record.name.split(' ').map(s=>s[0]).slice(0,2).join('')}</div>;}
function AppNav({section,onLogout}:{section:Section;onLogout:()=>Promise<void>}){
  const {setOpenMobile}=useSidebar();
  return <>
    <SidebarHeader className="school-sidebar-brand"><img src="/assets/school-logo.jpg" alt="Early Childhood logo" width="52" height="52"/><div><strong>Early Childhood</strong><span>Montessori</span></div></SidebarHeader>
    <SidebarContent><nav aria-label="Admin navigation" className="sidebar-nav"><SidebarMenu>{navigation.map(item=><SidebarMenuItem key={item.id}><SidebarMenuButton asChild isActive={section===item.id} className="school-nav-button"><Link href={item.id==='overview'?'/admin':`/admin/${item.id}`} onClick={()=>setOpenMobile(false)} aria-current={section===item.id?'page':undefined}><item.icon size={18}/><span>{item.label}</span></Link></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></nav></SidebarContent>
    <SidebarFooter className="school-sidebar-footer"><button type="button" onClick={onLogout}><LogOut size={19}/> Log out</button></SidebarFooter>
  </>;
}
type Editor={kind:Kind;record?:AdminRecord;category?:string};
type CreateCategory=(kind:CategoryKind,name:string)=>Promise<string>;
function mergeCategories(current:CategoryLists,next:CategoryLists):CategoryLists{
  return Object.fromEntries(categoryKinds.map(kind=>[kind,[...new Map([...next[kind],...current[kind]].map(name=>[normalizeCategory(name),name])).values()]])) as CategoryLists;
}
export default function AdminPortal({section,initial,account,onLogout}:{section:Section;initial:PortalData;account:{username:string;name:string|null};onLogout:()=>Promise<void>}){
  const router=useRouter();
  const [data,setData]=useState(initial),[editor,setEditor]=useState<Editor|null>(null),[remove,setRemove]=useState<AdminRecord|null>(null),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[team,setTeam]=useState('All'),[greeting,setGreeting]=useState('Welcome back'),[refreshing,setRefreshing]=useState(false),[live,setLive]=useState(false);
  const records=useMemo(()=>data.records.filter(record=>record.data.example!=='true'),[data.records]);
  const [category,setCategory]=useState('All'),[categoryDialog,setCategoryDialog]=useState<CategoryKind|null>(null);
  useEffect(()=>setData(initial),[initial]);
  useEffect(()=>{
    let stopped=false,running=false,queued=false;
    async function reload(){if(running){queued=true;return;}running=true;try{const value=await requestJson<PortalData>('/api/admin');if(!stopped)setData(prev=>({...value,categories:mergeCategories(prev.categories,value.categories)}));}catch{}finally{running=false;if(queued&&!stopped){queued=false;void reload();}}}
    const stopLive=subscribeLive('/api/admin/stream',reload,setLive,()=>window.dispatchEvent(new Event('admin-session-expired')));
    const timer=setInterval(reload,30000);window.addEventListener('focus',reload);
    return()=>{stopped=true;stopLive();clearInterval(timer);window.removeEventListener('focus',reload);};
  },[]);

  useEffect(()=>{setFilter('All');setSearch('');setTeam('All');setCategory('All');setCategoryDialog(null);},[section]);
  useEffect(()=>{const hour=Number(new Intl.DateTimeFormat('en',{hour:'numeric',hour12:false,timeZone:'Asia/Katmandu'}).format(new Date()));setGreeting(hour<12?'Good morning':hour<17?'Good afternoon':'Good evening');},[]);
  async function refresh(){setRefreshing(true);try{setData(await requestJson<PortalData>('/api/admin'));toast.success('Workspace refreshed');}catch(e){toast.error((e as Error).message);}finally{setRefreshing(false);}}
  function updateRecord(saved:AdminRecord){setData(prev=>({...prev,records:prev.records.some(r=>r.id===saved.id)?prev.records.map(r=>r.id===saved.id?saved:r):[saved,...prev.records]}));}
  async function save(kind:Kind,values:{name:string;status:string;data:Record<string,string>},record?:AdminRecord){
    const saved=await requestJson<AdminRecord>(`/api/records/${kind}${record?`/${record.id}`:''}`,record?'PATCH':'POST',{...values,...(record?{revision:record.revision}:{})});
    updateRecord(saved);if(!record&&isCategoryKind(kind)&&section===kind)setCategory(saved.data.category||'All');return saved as AdminRecord;
  }
  const createCategory:CreateCategory=async(kind,name)=>{
    const result=await requestJson<{name:string;created:boolean;categories:CategoryLists}>(`/api/categories/${kind}`,'POST',{name:categoryNameSchema.parse(name)});
    setData(prev=>({...prev,categories:mergeCategories(prev.categories,result.categories)}));
    toast.success(result.created?'Category created':'Existing category selected');return result.name;
  };
  async function changeStatus(record:AdminRecord,status:string){
    setBusy(true);try{await save(record.kind,{name:record.name,status,data:record.data},record);toast.success(`Marked ${status.toLowerCase()}`);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}
  }
  async function deleteRecord(){if(!remove)return;setBusy(true);try{await requestJson(`/api/records/${remove.kind}/${remove.id}`,'DELETE',{revision:remove.revision});setData(prev=>({...prev,records:prev.records.filter(r=>r.id!==remove.id)}));setRemove(null);toast.success('Record removed');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  const entity=section!=='overview'&&section!=='settings'?section:null;
  const visible=useMemo(()=>records.filter(r=>r.kind===entity&&(filter==='All'||r.status===filter)&&(category==='All'||recordCategories(r).some(name=>normalizeCategory(name)===normalizeCategory(category)))&&(entity!=='staff'||team==='All'||r.data.group===team)&&`${r.name} ${Object.values(r.data).join(' ')}`.toLowerCase().includes(search.toLowerCase())),[records,entity,filter,category,team,search]);
  const filtered=!!search||filter!=='All'||category!=='All'||team!=='All';
  function clearFilters(){setSearch('');setFilter('All');setCategory('All');setTeam('All');}
  const rowActions=(record:AdminRecord)=><div className="row-actions">{record.kind!=='reviews'&&<Button variant="ghost" size="icon" aria-label={`Edit ${record.name}`} onClick={()=>setEditor({kind:record.kind,record})}><Pencil size={16}/></Button>}<Button variant="ghost" size="icon" className="remove-button" aria-label={`Remove ${record.name}`} onClick={()=>setRemove(record)}><Trash2 size={16}/></Button></div>;
  const selectedTitle=section==='overview'?`${greeting}, ${data.settings.adminName}`:section==='settings'?'Settings':config[section].title;
  return <SidebarProvider style={{'--sidebar-width':'16.75rem'} as CSSProperties}>
    <Sidebar className="school-sidebar"><AppNav section={section} onLogout={onLogout}/></Sidebar>
    <SidebarInset className="admin-workspace">
      <a href="#workspace" className="skip-link">Skip to workspace</a>
      <header className="workspace-header"><div className="header-title"><SidebarTrigger className="mobile-menu"/><div><h1>{selectedTitle}</h1></div></div><div className="header-tools"><Link href="/admin/settings" className="account-button"><UserRound size={22}/><span>{data.settings.adminName}</span></Link></div></header>
      <div id="workspace" className="workspace-content" key={section}>
        {section==='overview'?<Overview records={records} onEdit={setEditor} onAdmission={r=>setEditor({kind:'admissions',record:r})} onNavigate={s=>router.push(`/admin/${s}`)}/>:section==='settings'?<SettingsForm data={data} account={account} onSaved={(settings,revision)=>setData(prev=>({...prev,settings,settingsRevision:revision}))}/>:entity&&<>
          <div className="section-toolbar"><div className="search-input"><Search size={18}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${config[entity].title.toLowerCase()}…`} aria-label={`Search ${config[entity].title}`}/></div><div className="toolbar-actions"><Choice value={filter} options={['All',...config[entity].statuses]} onChange={setFilter} label="Filter by status" allLabel="All statuses"/>{isCategoryKind(entity)&&<><Choice value={category} options={['All',...data.categories[entity]]} onChange={setCategory} label="Filter by category" allLabel="All categories"/><Button variant="outline" onClick={()=>setCategoryDialog(entity)}><Plus size={16}/>New category</Button></>}<Button variant="ghost" size="icon" onClick={refresh} disabled={refreshing} aria-label="Refresh records"><RefreshCw size={18} className={refreshing?'spinning':''}/></Button>{entity!=='reviews'&&<Button className="primary-button" onClick={()=>setEditor({kind:entity,...(category!=='All'?{category}:{})})}><Plus size={18}/><span>Add {config[entity].singular}</span></Button>}</div></div>
          {entity==='staff'&&<Tabs value={team} onValueChange={setTeam} className="team-tabs"><TabsList>{['All','Admins','Teachers','Operators'].map(t=><TabsTrigger value={t} key={t}>{t} <span>{records.filter(r=>r.kind==='staff'&&(t==='All'||r.data.group===t)).length}</span></TabsTrigger>)}</TabsList></Tabs>}
          <div className="records-caption"><span>{visible.length} {entity==='staff'?'team members':config[entity].title.toLowerCase()}</span></div>
          {visible.length===0?<div className="empty-state"><Inbox size={36}/><h2>{filtered?'No matching records':`No ${config[entity].title.toLowerCase()} yet`}</h2>{(entity!=='reviews'||filtered)&&<Button variant="outline" onClick={()=>{if(filtered)clearFilters();else setEditor({kind:entity});}}>{filtered?'Clear filters':`Add ${config[entity].singular}`}</Button>}</div>
          :entity==='staff'?<div className="staff-grid">{visible.map(record=><article className="staff-card" key={record.id}><div className="staff-card-top"><span className="group-tag">{record.data.group}</span><Status value={record.status}/></div><StaffAvatar record={record}/><h2>{record.name}</h2><p>{record.data.role}</p>{record.data.bio&&<p className="staff-bio">{record.data.bio}</p>}<div className="staff-card-bottom">{rowActions(record)}</div></article>)}</div>
          :entity==='gallery'?<div className="gallery-grid">{visible.map(record=><article className="gallery-card" key={record.id}><img src={record.data.imagePath} alt={record.data.alt} loading="lazy"/><div className="gallery-caption"><div><span>{record.data.category}</span><h2>{record.name}</h2><Status value={record.status}/></div>{rowActions(record)}</div></article>)}</div>
          :entity==='reviews'?<div className="reviews-grid">{visible.map(record=><article className="review-card" key={record.id}><div className="review-top"><span className="review-stars" aria-label={`${record.data.rating} out of 5 stars`}>{Array.from({length:5},(_,i)=><Star key={i} size={17} fill={i<Number(record.data.rating)?'currentColor':'none'}/>)}</span><Status value={record.status}/></div><blockquote>{record.data.body}</blockquote><p className="review-author">{record.name} </p><div className="review-bottom"><span>{dateLabel(record.data.date)}</span><div className="row-actions">{record.status!=='Approved'&&<Button variant="outline" disabled={busy} onClick={()=>changeStatus(record,'Approved')}><Check size={16}/>Approve</Button>}{record.status==='Approved'&&<Button variant="outline" disabled={busy} onClick={()=>changeStatus(record,'Hidden')}>Hide</Button>}{rowActions(record)}</div></div></article>)}</div>
          :<section className="panel records-table"><Table><TableHeader><TableRow><TableHead>{entity==='admissions'?'Applicant':entity==='programs'?'Program':'Title'}</TableHead><TableHead>{entity==='admissions'?'Program':entity==='programs'?'Age group':entity==='events'?'Date & time':'Author'}</TableHead><TableHead>{entity==='programs'?'Monthly fee':'Date / location'}</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{visible.map(record=><TableRow key={record.id}><TableCell><button className="table-record-name" onClick={()=>setEditor({kind:entity,record})}>{record.name}</button>{entity==='blog'&&<p className="table-excerpt">{record.data.excerpt}</p>}</TableCell><TableCell>{entity==='admissions'?record.data.program:entity==='programs'?record.data.age:entity==='events'?`${dateLabel(record.data.date)} ${record.data.time}`:record.data.author}</TableCell><TableCell>{entity==='programs'?(record.data.fee?`Rs ${Number(record.data.fee).toLocaleString()}`:'Not set'):entity==='events'?record.data.location:dateLabel(record.data.date)}</TableCell><TableCell><Status value={record.status}/></TableCell><TableCell>{rowActions(record)}</TableCell></TableRow>)}</TableBody></Table></section>}
          
        </>}
      </div>
      <footer className="workspace-footer"><span>Admin Dashboard · Early Childhood Montessori</span><span><ShieldCheck size={14}/>{live?'Online':'Reconnecting…'}</span></footer>
    </SidebarInset>
    {editor&&<RecordEditor editor={editor} categories={data.categories} onCreateCategory={createCategory} onClose={()=>setEditor(null)} onSave={save}/>}
    {categoryDialog&&<NewCategoryDialog kind={categoryDialog} onCreate={createCategory} onClose={()=>setCategoryDialog(null)} onCreated={name=>{setCategory(name);setCategoryDialog(null);}}/>}
    <AlertDialog open={!!remove} onOpenChange={open=>{if(!open&&!busy)setRemove(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove {remove?.name}?</AlertDialogTitle><AlertDialogDescription>This removes the record from this admin workspace. This action cannot be undone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep record</AlertDialogCancel><Button className="delete-confirm" onClick={deleteRecord} disabled={busy}>{busy?'Removing…':'Remove record'}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Toaster position="bottom-right" richColors closeButton/>
  </SidebarProvider>;
}
function Choice({value,options,onChange,label,id,allLabel}:{value:string;options:string[];onChange:(value:string)=>void;label:string;id?:string;allLabel?:string}){return <Select value={value} onValueChange={next=>{if(options.includes(next))onChange(next);}}><SelectTrigger id={id} className="choice" aria-label={label}><SelectValue placeholder={`Choose ${label.toLowerCase()}`}/></SelectTrigger><SelectContent position="popper">{options.map(value=><SelectItem key={value} value={value}>{value==='All'&&allLabel?allLabel:value}</SelectItem>)}</SelectContent></Select>;}
function NewCategoryDialog({kind,onCreate,onClose,onCreated}:{kind:CategoryKind;onCreate:CreateCategory;onClose:()=>void;onCreated:(name:string)=>void}){
  const [name,setName]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{onCreated(await onCreate(kind,name));}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  return <Dialog open onOpenChange={open=>{if(!open&&!saving)onClose();}}><DialogContent aria-describedby={undefined} className="category-dialog" showCloseButton={!saving} onInteractOutside={event=>{if(saving)event.preventDefault();}} onEscapeKeyDown={event=>{if(saving)event.preventDefault();}}><DialogHeader><DialogTitle>New {config[kind].title.toLowerCase()} category</DialogTitle></DialogHeader><form onSubmit={submit}><div className="form-field"><label htmlFor="new-category-name">Category name</label><Input id="new-category-name" value={name} onChange={e=>{setName(e.target.value);setError('');}} required maxLength={80} autoFocus disabled={saving}/></div>{error&&<p className="form-error" role="alert">{error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={onClose} disabled={saving}>Cancel</Button><Button type="submit" className="primary-button" disabled={saving}>{saving?'Creating…':'Create category'}</Button></DialogFooter></form></DialogContent></Dialog>;
}
function CategoryField({kind,id,value,options,onChange,onCreate}:{kind:CategoryKind;id:string;value:string;options:string[];onChange:(value:string)=>void;onCreate:CreateCategory}){
  const [adding,setAdding]=useState(false),[name,setName]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
  async function create(){setSaving(true);setError('');try{onChange(await onCreate(kind,name));setAdding(false);setName('');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  return <div className="category-field"><div className="category-select"><Choice id={id} value={value} options={options} onChange={onChange} label="Category"/><Button type="button" variant="outline" disabled={saving} onClick={()=>setAdding(true)}><Plus size={14}/>New category</Button></div>{adding&&<div className="inline-category"><label htmlFor={`${id}-new`}>New category name</label><Input id={`${id}-new`} value={name} onChange={e=>{setName(e.target.value);setError('');}} maxLength={80} autoFocus disabled={saving} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void create();}}}/><div className="inline-category-actions"><Button type="button" variant="outline" onClick={()=>{setAdding(false);setError('');}} disabled={saving}>Cancel category</Button><Button type="button" onClick={create} disabled={saving}>{saving?'Creating…':'Create category'}</Button></div>{error&&<p className="form-error" role="alert">{error}</p>}</div>}</div>;
}
function Overview({records,onEdit,onAdmission,onNavigate}:{records:AdminRecord[];onEdit:(editor:Editor)=>void;onAdmission:(record:AdminRecord)=>void;onNavigate:(section:Section)=>void}){
  const admissions=records.filter(r=>r.kind==='admissions').sort((a,b)=>(b.data.date??'').localeCompare(a.data.date??''));
  const month=today().slice(0,7);
  const stats=[{label:'New Admissions',value:admissions.filter(r=>r.data.date?.startsWith(month)).length,caption:'This month',tone:'blue',section:'admissions'},
    {label:'Students',value:admissions.filter(r=>r.status==='Approved').length,caption:'Approved applications',tone:'green',section:'admissions'},
    {label:'Team Members',value:records.filter(r=>r.kind==='staff'&&r.status==='Active').length,caption:'Active staff',tone:'coral',section:'staff'},
    {label:'Upcoming Events',value:records.filter(r=>r.kind==='events'&&r.status==='Published'&&r.data.date>=today()).length,caption:'Scheduled activities',tone:'blue',section:'events'}];
  const content=[['Published Programs',records.filter(r=>r.kind==='programs'&&r.status==='Published').length],['Team Profiles',records.filter(r=>r.kind==='staff').length],['Gallery Items',records.filter(r=>r.kind==='gallery').length],['Upcoming Events',records.filter(r=>r.kind==='events'&&r.status==='Published'&&r.data.date>=today()).length]];
  return <>
    <section className="overview-section"><h2 className="section-label">Overview</h2><div className="overview-stats">{stats.map((stat,i)=><button className="stat" key={stat.label} style={{'--order':i} as CSSProperties} onClick={()=>onNavigate(stat.section as Section)}><span className="stat-label">{stat.label}<i className={`stat-dot ${stat.tone}`}/></span><strong>{stat.value.toString().padStart(2,'0')}</strong><span className="stat-caption">{stat.caption}</span></button>)}</div></section>
    <section className="dashboard-main panel"><div className="recent-admissions"><div className="panel-heading"><div><h2>Recent Admissions</h2></div><Button variant="ghost" className="view-all" onClick={()=>onNavigate('admissions')}>View all</Button></div><Table><TableHeader><TableRow><TableHead>Applicant</TableHead><TableHead>Program</TableHead><TableHead>Date</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{admissions.slice(0,5).map(record=><TableRow key={record.id} onClick={()=>onAdmission(record)} className="admission-row"><TableCell><button onClick={event=>{event.stopPropagation();onAdmission(record);}} className="table-record-name">{record.name}</button></TableCell><TableCell>{record.data.program}</TableCell><TableCell>{dateLabel(record.data.date)}</TableCell><TableCell><Status value={record.status}/></TableCell></TableRow>)}</TableBody></Table>{!admissions.length&&<p className="table-empty">No applications yet.</p>}</div><aside className="dashboard-right"><section className="quick-actions"><h2>Quick Actions</h2><button onClick={()=>onEdit({kind:'staff'})}><Users size={17}/><span>Add Team Member</span><Plus size={16}/></button><button onClick={()=>onEdit({kind:'events'})}><CalendarDays size={17}/><span>Create Event</span><Plus size={16}/></button><button onClick={()=>onEdit({kind:'blog'})}><FileText size={17}/><span>Create Blog</span><Plus size={16}/></button></section><section className="content-summary"><h2>Workspace Content</h2><dl>{content.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section></aside></section>
    <section className="admin-controls panel"><div><h2>Admin Controls</h2></div>{[{title:'Staff & Teachers',icon:Users,section:'staff',tone:'blue'},{title:'Reviews',icon:Star,section:'reviews',tone:'green'},{title:'Gallery',icon:Images,section:'gallery',tone:'coral'},{title:'Pending',icon:ClipboardList,section:'admissions',tone:'blue'}].map(item=><button key={item.title} onClick={()=>onNavigate(item.section as Section)}><span><item.icon size={17} className={`control-icon ${item.tone}`}/><strong>{item.title}</strong></span></button>)}</section>
    
  </>;
}
function RecordEditor({editor,categories,onCreateCategory,onClose,onSave}:{editor:Editor;categories:CategoryLists;onCreateCategory:CreateCategory;onClose:()=>void;onSave:(kind:Kind,values:{name:string;status:string;data:Record<string,string>},record?:AdminRecord)=>Promise<AdminRecord>}){
  const {kind,record}=editor,definition=config[kind];
  const [name,setName]=useState(record?.name??''),[status,setStatus]=useState(record?.status??definition.statuses[0]),[values,setValues]=useState<Record<string,string>>(()=>({...Object.fromEntries(definition.fields.map(field=>[field.key,field.type==='date'?today():field.type==='category'&&isCategoryKind(kind)?editor.category??categories[kind][0]??'':field.options?.[0]??''])),...record?.data})),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(record?.data.imagePath??''),[saving,setSaving]=useState(false),[error,setError]=useState('');
  const [categoryCreating,setCategoryCreating]=useState(false);
  const locked=saving||categoryCreating;
  const createCategoryForEditor:CreateCategory=async(kind,name)=>{setCategoryCreating(true);try{return await onCreateCategory(kind,name);}finally{setCategoryCreating(false);}};
  useEffect(()=>{if(!file)return;const url=URL.createObjectURL(file);setPreview(url);return ()=>URL.revokeObjectURL(url);},[file]);
  function update(key:string,value:string){setValues(prev=>({...prev,[key]:value}));setError('');}
  async function submit(event:FormEvent){event.preventDefault();if(categoryCreating)return;setError('');setSaving(true);try{
    const data={...values};
    if(kind==='gallery'&&record&&normalizeCategory(data.category)!==normalizeCategory(record.data.category))data.categories=[data.category,...recordCategories(record).filter(name=>normalizeCategory(name)!==normalizeCategory(record.data.category)&&normalizeCategory(name)!==normalizeCategory(data.category))].join(',');
    if(file){const response=await fetch('/api/uploads',{method:'POST',headers:{'Content-Type':file.type,'X-File-Name':encodeURIComponent(file.name)},body:file});const result=await response.json() as {error?:string;imagePath:string};if(!response.ok)throw new Error(result.error??'Could not upload the photo.');data.imagePath=result.imagePath;setValues(data);setFile(null);setPreview(result.imagePath);}
    validateRecord(kind,{name,status,data},categories);
    await onSave(kind,{name,status,data},record);toast.success(record?'Changes saved':`${titleCase(definition.singular)} added`);onClose();
  }catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  function renderField(field:Field){const id=`editor-${field.key}`;return <div className={`form-field ${field.type==='textarea'?'full-width':''}`} key={field.key}><label htmlFor={id}>{field.label}{field.required&&<span> *</span>}</label>{field.type==='category'&&isCategoryKind(kind)?<CategoryField kind={kind} id={id} value={values[field.key]??''} options={categories[kind]} onChange={v=>update(field.key,v)} onCreate={createCategoryForEditor}/>:field.type==='select'?<Choice id={id} value={values[field.key]??''} options={field.options??[]} onChange={v=>update(field.key,v)} label={field.label}/>:field.type==='textarea'?<Textarea id={id} value={values[field.key]??''} onChange={e=>update(field.key,e.target.value)} required={field.required} maxLength={12000} rows={kind==='blog'&&field.key==='body'?9:4}/>:field.key==='phone'?<div className="nepal-phone"><span>+977</span><Input id={id} type="tel" inputMode="numeric" pattern="[0-9]{10}" maxLength={10} title="Enter exactly 10 digits after +977" value={values[field.key]??''} onChange={e=>update(field.key,e.target.value.replace(/[^0-9]/g,''))} required={field.required}/></div>:<Input id={id} type={field.type??'text'} value={values[field.key]??''} onChange={e=>update(field.key,e.target.value)} required={field.required} maxLength={300} min={field.min} max={field.key==='birthDate'?today():field.max} step={field.type==='number'?'1':undefined}/>}</div>;}
  return <Dialog open onOpenChange={open=>{if(!open&&!locked)onClose();}}><DialogContent aria-describedby={undefined} className="editor-dialog" onInteractOutside={event=>{if(locked)event.preventDefault();}} onEscapeKeyDown={event=>{if(locked)event.preventDefault();}} showCloseButton={!locked}><DialogHeader><DialogTitle>{record?'Edit':'Add'} {definition.singular}</DialogTitle></DialogHeader><form onSubmit={submit} className="editor-form"><div className="form-grid"><div className="form-field full-width"><label htmlFor="record-name">{definition.nameLabel} *</label><Input id="record-name" autoFocus value={name} onChange={e=>{setName(e.target.value);setError('');}} required minLength={2} maxLength={160}/></div>{definition.fields.map(renderField)}<div className="form-field"><label htmlFor="record-status">Status</label><Choice id="record-status" value={status} options={definition.statuses} onChange={setStatus} label="Status"/></div>{(kind==='staff'||kind==='gallery'||kind==='blog')&&<div className="form-field full-width"><label htmlFor="record-photo">{kind==='gallery'?'Photo *':kind==='blog'?'Article photo':'Profile photo'}</label><div className="photo-upload">{preview&&<img src={preview} alt="Selected photo preview"/>}<div><Input id="record-photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const selected=e.target.files?.[0]??null;if(selected&&selected.size>8*1024*1024){setError('Choose a photo smaller than 8 MB.');e.target.value='';return;}setFile(selected);setError('');}}/><p>JPEG, PNG, or WebP · up to 8 MB</p></div></div></div>}</div>{error&&<p className="form-error" role="alert">{error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={onClose} disabled={locked}>Cancel</Button><Button type="submit" className="primary-button" disabled={locked}>{categoryCreating?'Creating category…':saving?'Saving…':record?'Save changes':`Add ${definition.singular}`}</Button></DialogFooter></form></DialogContent></Dialog>;
}
function SettingsForm({data,account,onSaved}:{data:PortalData;account:{username:string;name:string|null};onSaved:(settings:Settings,revision:number)=>void}){
  const [settings,setSettings]=useState(data.settings),[revision,setRevision]=useState(data.settingsRevision),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(!dirty){setSettings(data.settings);setRevision(data.settingsRevision);}},[data.settings,data.settingsRevision,dirty]);
  async function submit(event:FormEvent){event.preventDefault();setError('');setSaving(true);try{const valid=settingsSchema.safeParse(settings);if(!valid.success)throw new Error(valid.error.issues[0].message);const result=await requestJson<{settings:Settings;settingsRevision:number}>('/api/settings','PATCH',{settings:valid.data,revision});onSaved(result.settings,result.settingsRevision);setRevision(result.settingsRevision);setDirty(false);toast.success('Settings saved');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  const field=(key:keyof Settings,label:string,type='text')=><div className="form-field" key={key}><label htmlFor={`settings-${key}`}>{label}</label>{key==='phone'?<output id={`settings-${key}`} className="school-landline">{settings.phone}</output>:<Input id={`settings-${key}`} type={type} value={settings[key]} onChange={e=>{setDirty(true);setSettings(prev=>({...prev,[key]:e.target.value}));}} maxLength={key==='address'?300:120} required/>}</div>;
  return <div className="settings-layout"><section className="panel settings-panel"><h2>School Details</h2><form onSubmit={submit}><div className="form-grid">{field('schoolName','School name')}{field('adminName','Admin display name')}{field('email','School email','email')}{field('phone','School landline (Nepal +977)')}{field('address','Address')}{field('workingDays','Working days')}{field('openTime','Opening time','time')}{field('closeTime','Closing time','time')}</div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="settings-actions"><Button type="submit" className="primary-button" disabled={saving}>{saving?'Saving…':'Save settings'}</Button></div></form></section><aside className="settings-aside"><section className="panel"><ShieldCheck size={27}/><h2>Admin Account</h2><strong>{account.name??data.settings.adminName}</strong><p className="account-email">{account.username}</p><span className="status status-active">Administrator</span><p className="secondary-text">Recovery email: {data.recoveryEmail||'Not set'}</p><PasswordForm/></section><section className="settings-connection"><h2>Email delivery</h2><p>{data.mail?.configured?'Email available':'Email unavailable'}</p><p>{data.mail?.pending??0} emails pending · {data.mail?.failed??0} failed</p><Button variant="outline" onClick={async()=>{try{await requestJson('/api/mail/retry','POST');toast.success('Emails queued');}catch(e){toast.error((e as Error).message);}}}>Retry pending emails</Button><p><Clock size={16}/> {data.settings.workingDays}<br/>{timeLabel(data.settings.openTime)} – {timeLabel(data.settings.closeTime)}</p></section></aside></div>;
}
