'use client';
import { useEffect,useMemo,useState,type FormEvent,type CSSProperties } from 'react';
import { Link,useRouter } from './navigation';
import { Bell,UserRound,LayoutGrid,ClipboardList,Users,Star,Mail,BookOpen,Images,CalendarDays,FileText,Settings as SettingsIcon,LogOut,Plus,Search,Pencil,Trash2,Check,Upload,RefreshCw,Eye,Menu,ShieldCheck,Clock,Inbox,X } from 'lucide-react';
import { SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar } from '@/components/ui/sidebar';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel } from '@/components/ui/alert-dialog';
import { Table,TableHeader,TableHead,TableBody,TableRow,TableCell } from '@/components/ui/table';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Skeleton } from '@/components/ui/skeleton';
import { Toaster,toast } from 'sonner';
import { config,kinds,dateLabel,settingsSchema,validateRecord,type AdminRecord,type Kind,type PortalData,type Section,type Settings,type Field } from './admin-model';

const navigation=[
  {id:'overview',label:'Quick Actions',icon:LayoutGrid},{id:'admissions',label:'Admissions',icon:ClipboardList},{id:'staff',label:'Staff & Teachers',icon:Users},{id:'reviews',label:'Reviews',icon:Star},{id:'messages',label:'Messages',icon:Mail},{id:'programs',label:'Programs',icon:BookOpen},{id:'gallery',label:'Gallery',icon:Images},{id:'events',label:'Events',icon:CalendarDays},{id:'blog',label:'Blog',icon:FileText},{id:'settings',label:'Settings',icon:SettingsIcon},
] as const;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Katmandu',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const timeLabel=(value:string)=>new Intl.DateTimeFormat('en',{hour:'numeric',minute:'2-digit',hour12:true,timeZone:'UTC'}).format(new Date(`2000-01-01T${value}:00Z`));
const titleCase=(text:string)=>text.charAt(0).toUpperCase()+text.slice(1);
async function requestJson<T=unknown>(url:string,method='GET',body?:unknown):Promise<T>{
  const response=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});
  let data:unknown;try{data=await response.json();}catch{throw new Error('Your session may have expired. Reload and sign in again.');}
  if(response.status===401)window.dispatchEvent(new Event('admin-session-expired'));
  if(!response.ok)throw new Error((data as {error?:string})?.error??'Could not save your changes.');
  return data as T;
}
function Status({value}:{value:string}){return <span className={`status status-${value.toLowerCase()}`}>{value}</span>;}
function Example({record}:{record:AdminRecord}){return record.data.example==='true'?<span className="example-tag">Example</span>:null;}
function StaffAvatar({record}:{record:AdminRecord}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[record.data.imagePath]);return <div className="staff-avatar">{record.data.imagePath&&!failed?<img src={record.data.imagePath} alt={record.name} loading="lazy" onError={()=>setFailed(true)}/>:record.name.split(' ').map(s=>s[0]).slice(0,2).join('')}</div>;}
function AppNav({section,unread,onLogout}:{section:Section;unread:number;onLogout:()=>Promise<void>}){
  const {setOpenMobile}=useSidebar();
  return <>
    <SidebarHeader className="school-sidebar-brand"><img src="/assets/school-logo.jpg" alt="Early Childhood logo" width="52" height="52"/><div><strong>Early Childhood</strong><span>Montessori</span></div></SidebarHeader>
    <SidebarContent><nav aria-label="Admin navigation" className="sidebar-nav"><SidebarMenu>{navigation.map(item=><SidebarMenuItem key={item.id}><SidebarMenuButton asChild isActive={section===item.id} className="school-nav-button"><Link href={item.id==='overview'?'/admin':`/admin/${item.id}`} onClick={()=>setOpenMobile(false)} aria-current={section===item.id?'page':undefined}><item.icon size={18}/><span>{item.label}</span>{item.id==='messages'&&unread>0&&<b className="nav-count">{unread}</b>}</Link></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></nav></SidebarContent>
    <SidebarFooter className="school-sidebar-footer"><button type="button" onClick={onLogout}><LogOut size={19}/> Log out</button></SidebarFooter>
  </>;
}
type Editor={kind:Kind;record?:AdminRecord};
export default function AdminPortal({section,initial,account,onLogout}:{section:Section;initial:PortalData;account:{username:string;name:string|null};onLogout:()=>Promise<void>}){
  const router=useRouter();
  const [data,setData]=useState(initial),[editor,setEditor]=useState<Editor|null>(null),[remove,setRemove]=useState<AdminRecord|null>(null),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[team,setTeam]=useState('All'),[message,setMessage]=useState<AdminRecord|null>(null),[greeting,setGreeting]=useState('Welcome back'),[refreshing,setRefreshing]=useState(false);
  const records=data.records;
  const unread=records.filter(r=>r.kind==='messages'&&r.status==='Unread').length;
  useEffect(()=>setData(initial),[initial]);
  useEffect(()=>{setFilter('All');setSearch('');setTeam('All');},[section]);
  useEffect(()=>{const hour=Number(new Intl.DateTimeFormat('en',{hour:'numeric',hour12:false,timeZone:'Asia/Katmandu'}).format(new Date()));setGreeting(hour<12?'Good morning':hour<17?'Good afternoon':'Good evening');},[]);
  async function refresh(){setRefreshing(true);try{setData(await requestJson<PortalData>('/api/admin'));toast.success('Workspace refreshed');}catch(e){toast.error((e as Error).message);}finally{setRefreshing(false);}}
  function updateRecord(saved:AdminRecord){setData(prev=>({...prev,records:prev.records.some(r=>r.id===saved.id)?prev.records.map(r=>r.id===saved.id?saved:r):[saved,...prev.records]}));}
  async function save(kind:Kind,values:{name:string;status:string;data:Record<string,string>},record?:AdminRecord){
    const saved=await requestJson<AdminRecord>(`/api/records/${kind}${record?`/${record.id}`:''}`,record?'PATCH':'POST',{...values,...(record?{revision:record.revision}:{})});
    updateRecord(saved);return saved as AdminRecord;
  }
  async function changeStatus(record:AdminRecord,status:string){
    setBusy(true);try{const saved=await save(record.kind,{name:record.name,status,data:record.data},record);setMessage(current=>current?.id===record.id?saved:current);toast.success(`Marked ${status.toLowerCase()}`);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}
  }
  async function deleteRecord(){if(!remove)return;setBusy(true);try{await requestJson(`/api/records/${remove.kind}/${remove.id}`,'DELETE',{revision:remove.revision});setData(prev=>({...prev,records:prev.records.filter(r=>r.id!==remove.id)}));setRemove(null);toast.success('Record removed');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function openMessage(record:AdminRecord){setMessage(record);if(record.status==='Unread')await changeStatus(record,'Read');}
  const entity=section!=='overview'&&section!=='settings'?section:null;
  const visible=useMemo(()=>records.filter(r=>r.kind===entity&&(filter==='All'||r.status===filter)&&(entity!=='staff'||team==='All'||r.data.group===team)&&`${r.name} ${Object.values(r.data).join(' ')}`.toLowerCase().includes(search.toLowerCase())),[records,entity,filter,team,search]);
  const rowActions=(record:AdminRecord)=><div className="row-actions"><Button variant="ghost" size="icon" aria-label={`Edit ${record.name}`} onClick={()=>setEditor({kind:record.kind,record})}><Pencil size={16}/></Button><Button variant="ghost" size="icon" className="remove-button" aria-label={`Remove ${record.name}`} onClick={()=>setRemove(record)}><Trash2 size={16}/></Button></div>;
  const selectedTitle=section==='overview'?`${greeting}, ${data.settings.adminName}`:section==='settings'?'Settings':config[section].title;
  return <SidebarProvider style={{'--sidebar-width':'16.75rem'} as CSSProperties}>
    <Sidebar className="school-sidebar"><AppNav section={section} unread={unread} onLogout={onLogout}/></Sidebar>
    <SidebarInset className="admin-workspace">
      <a href="#workspace" className="skip-link">Skip to workspace</a>
      <header className="workspace-header"><div className="header-title"><SidebarTrigger className="mobile-menu"/><div><h1>{selectedTitle}</h1><p>{section==='overview'?'Your school, organized in one place.':section==='settings'?'Update school details and your admin preferences.':config[section].description}</p></div></div><div className="header-tools"><Button variant="ghost" size="icon" className="notification-button" aria-label={`${unread} unread messages`} onClick={()=>router.push('/admin/messages')}><Bell size={23}/>{unread>0&&<span/>}</Button><Link href="/admin/settings" className="account-button"><UserRound size={22}/><span>{data.settings.adminName}</span></Link></div></header>
      <div id="workspace" className="workspace-content" key={section}>
        {section==='overview'?<Overview records={records} onEdit={setEditor} onAdmission={r=>setEditor({kind:'admissions',record:r})} onNavigate={s=>router.push(`/admin/${s}`)}/>:section==='settings'?<SettingsForm data={data} account={account} onSaved={(settings,revision)=>setData(prev=>({...prev,settings,settingsRevision:revision}))}/>:entity&&<>
          <div className="section-toolbar"><div className="search-input"><Search size={18}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${config[entity].title.toLowerCase()}…`} aria-label={`Search ${config[entity].title}`}/></div><div className="toolbar-actions"><Choice value={filter} options={['All',...config[entity].statuses]} onChange={setFilter} label="Filter by status"/><Button variant="ghost" size="icon" onClick={refresh} disabled={refreshing} aria-label="Refresh records"><RefreshCw size={18} className={refreshing?'spinning':''}/></Button><Button className="primary-button" onClick={()=>setEditor({kind:entity})}><Plus size={18}/><span>Add {config[entity].singular}</span></Button></div></div>
          {entity==='staff'&&<Tabs value={team} onValueChange={setTeam} className="team-tabs"><TabsList>{['All','Admins','Teachers','Operators'].map(t=><TabsTrigger value={t} key={t}>{t} <span>{records.filter(r=>r.kind==='staff'&&(t==='All'||r.data.group===t)).length}</span></TabsTrigger>)}</TabsList></Tabs>}
          <div className="records-caption"><span>{visible.length} {entity==='staff'?'team members':config[entity].title.toLowerCase()}</span>{['admissions','messages','reviews'].includes(entity)&&<span>Rows marked Example contain sample data.</span>}</div>
          {visible.length===0?<div className="empty-state"><Inbox size={36}/><h2>{search||filter!=='All'||team!=='All'?'No matching records':`No ${config[entity].title.toLowerCase()} yet`}</h2><p>{search||filter!=='All'||team!=='All'?'Try another search or filter.':`Add your first ${config[entity].singular} to get started.`}</p><Button variant="outline" onClick={()=>{if(search||filter!=='All'||team!=='All'){setSearch('');setFilter('All');setTeam('All');}else setEditor({kind:entity});}}>{search||filter!=='All'||team!=='All'?'Clear filters':`Add ${config[entity].singular}`}</Button></div>
          :entity==='staff'?<div className="staff-grid">{visible.map(record=><article className="staff-card" key={record.id}><div className="staff-card-top"><span className="group-tag">{record.data.group}</span><Status value={record.status}/></div><StaffAvatar record={record}/><h2>{record.name}</h2><p>{record.data.role}</p>{record.data.bio&&<p className="staff-bio">{record.data.bio}</p>}<div className="staff-card-bottom">{rowActions(record)}</div></article>)}</div>
          :entity==='gallery'?<div className="gallery-grid">{visible.map(record=><article className="gallery-card" key={record.id}><img src={record.data.imagePath} alt={record.data.alt} loading="lazy"/><div className="gallery-caption"><div><span>{record.data.category}</span><h2>{record.name}</h2><Status value={record.status}/></div>{rowActions(record)}</div></article>)}</div>
          :entity==='messages'?<div className="message-list">{visible.map(record=><article className={`message-row ${record.status==='Unread'?'unread':''}`} key={record.id}><button className="message-open" onClick={()=>openMessage(record)}><span className="message-avatar"><Mail size={21}/></span><div><h2>{record.data.subject}</h2><p>{record.name} <Example record={record}/></p><span className="message-preview">{record.data.body}</span></div></button><div className="message-meta"><span>{dateLabel(record.data.date)}</span><Status value={record.status}/>{rowActions(record)}</div></article>)}</div>
          :entity==='reviews'?<div className="reviews-grid">{visible.map(record=><article className="review-card" key={record.id}><div className="review-top"><span className="review-stars" aria-label={`${record.data.rating} out of 5 stars`}>{Array.from({length:5},(_,i)=><Star key={i} size={17} fill={i<Number(record.data.rating)?'currentColor':'none'}/>)}</span><Status value={record.status}/></div><blockquote>{record.data.body}</blockquote><p className="review-author">{record.name} <Example record={record}/></p><div className="review-bottom"><span>{dateLabel(record.data.date)}</span><div className="row-actions">{record.status==='Pending'&&<Button variant="outline" disabled={busy} onClick={()=>changeStatus(record,'Approved')}><Check size={16}/>Approve</Button>}{rowActions(record)}</div></div></article>)}</div>
          :<section className="panel records-table"><Table><TableHeader><TableRow><TableHead>{entity==='admissions'?'Applicant':entity==='programs'?'Program':'Title'}</TableHead><TableHead>{entity==='admissions'?'Program':entity==='programs'?'Age group':entity==='events'?'Date & time':'Author'}</TableHead><TableHead>{entity==='programs'?'Monthly fee':'Date / location'}</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{visible.map(record=><TableRow key={record.id}><TableCell><button className="table-record-name" onClick={()=>setEditor({kind:entity,record})}>{record.name}</button><Example record={record}/>{entity==='blog'&&<p className="table-excerpt">{record.data.excerpt}</p>}</TableCell><TableCell>{entity==='admissions'?record.data.program:entity==='programs'?record.data.age:entity==='events'?`${dateLabel(record.data.date)} ${record.data.time}`:record.data.author}</TableCell><TableCell>{entity==='programs'?(record.data.fee?`Rs ${Number(record.data.fee).toLocaleString()}`:'Not set'):entity==='events'?record.data.location:dateLabel(record.data.date)}</TableCell><TableCell><Status value={record.status}/></TableCell><TableCell>{rowActions(record)}</TableCell></TableRow>)}</TableBody></Table></section>}
          <p className="independent-note">Changes are saved locally on this computer.</p>
        </>}
      </div>
      <footer className="workspace-footer"><span>Admin Dashboard · Early Childhood Montessori</span><span><ShieldCheck size={14}/> Local workspace</span></footer>
    </SidebarInset>
    {editor&&<RecordEditor editor={editor} onClose={()=>setEditor(null)} onSave={save}/>}
    <AlertDialog open={!!remove} onOpenChange={open=>{if(!open&&!busy)setRemove(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove {remove?.name}?</AlertDialogTitle><AlertDialogDescription>This removes the record from this admin workspace. This action cannot be undone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep record</AlertDialogCancel><Button className="delete-confirm" onClick={deleteRecord} disabled={busy}>{busy?'Removing…':'Remove record'}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Dialog open={!!message} onOpenChange={open=>{if(!open)setMessage(null);}}><DialogContent className="message-dialog"><DialogHeader><DialogTitle>{message?.data.subject}</DialogTitle><DialogDescription>{message?.name}{message?.data.email?` · ${message.data.email}`:''}</DialogDescription></DialogHeader>{message&&<><Status value={message.status}/><div className="message-body">{message.data.body}</div><span className="secondary-text">{dateLabel(message.data.date)} <Example record={message}/></span><DialogFooter><Button variant="outline" disabled={busy} onClick={()=>changeStatus(message,message.status==='Resolved'?'Read':'Resolved')}>{message.status==='Resolved'?'Mark as read':'Mark resolved'}</Button>{message.data.email&&<a className="primary-button" href={`mailto:${encodeURIComponent(message.data.email)}?subject=${encodeURIComponent(`Re: ${message.data.subject}`)}`}>Open reply email</a>}</DialogFooter></>}</DialogContent></Dialog>
    <Toaster position="bottom-right" richColors closeButton/>
  </SidebarProvider>;
}
function Choice({value,options,onChange,label,id}:{value:string;options:string[];onChange:(value:string)=>void;label:string;id?:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger id={id} className="choice" aria-label={label}><SelectValue/></SelectTrigger><SelectContent position="popper">{options.map(value=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select>;}
function Overview({records,onEdit,onAdmission,onNavigate}:{records:AdminRecord[];onEdit:(editor:Editor)=>void;onAdmission:(record:AdminRecord)=>void;onNavigate:(section:Section)=>void}){
  const admissions=records.filter(r=>r.kind==='admissions').sort((a,b)=>(b.data.date??'').localeCompare(a.data.date??''));
  const month=today().slice(0,7);
  const stats=[{label:'New Admissions',value:admissions.filter(r=>r.data.date?.startsWith(month)).length,caption:'This month',tone:'blue',section:'admissions'},
    {label:'Students',value:admissions.filter(r=>r.status==='Approved').length,caption:'Approved applications',tone:'green',section:'admissions'},
    {label:'Team Members',value:records.filter(r=>r.kind==='staff'&&r.status==='Active').length,caption:'Active staff',tone:'coral',section:'staff'},
    {label:'Messages',value:records.filter(r=>r.kind==='messages'&&r.status==='Unread').length,caption:'Need attention',tone:'blue',section:'messages'}];
  const content=[['Published Programs',records.filter(r=>r.kind==='programs'&&r.status==='Published').length],['Team Profiles',records.filter(r=>r.kind==='staff').length],['Gallery Items',records.filter(r=>r.kind==='gallery').length],['Upcoming Events',records.filter(r=>r.kind==='events'&&r.status==='Published'&&r.data.date>=today()).length],['Unread Messages',records.filter(r=>r.kind==='messages'&&r.status==='Unread').length]];
  return <>
    <section className="overview-section"><h2 className="section-label">Overview</h2><div className="overview-stats">{stats.map((stat,i)=><button className="stat" key={stat.label} style={{'--order':i} as CSSProperties} onClick={()=>onNavigate(stat.section as Section)}><span className="stat-label">{stat.label}<i className={`stat-dot ${stat.tone}`}/></span><strong>{stat.value.toString().padStart(2,'0')}</strong><span className="stat-caption">{stat.caption}</span></button>)}</div></section>
    <section className="dashboard-main panel"><div className="recent-admissions"><div className="panel-heading"><div><h2>Recent Admissions</h2><p>Latest applications in your admin workspace</p></div><Button variant="ghost" className="view-all" onClick={()=>onNavigate('admissions')}>View all</Button></div><Table><TableHeader><TableRow><TableHead>Applicant</TableHead><TableHead>Program</TableHead><TableHead>Date</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{admissions.slice(0,5).map(record=><TableRow key={record.id} onClick={()=>onAdmission(record)} className="admission-row"><TableCell><button onClick={event=>{event.stopPropagation();onAdmission(record);}} className="table-record-name">{record.name}</button><Example record={record}/></TableCell><TableCell>{record.data.program}</TableCell><TableCell>{dateLabel(record.data.date)}</TableCell><TableCell><Status value={record.status}/></TableCell></TableRow>)}</TableBody></Table>{!admissions.length&&<p className="table-empty">No applications yet. Add one in Admissions.</p>}</div><aside className="dashboard-right"><section className="quick-actions"><h2>Quick Actions</h2><button onClick={()=>onEdit({kind:'staff'})}><Users size={17}/><span>Add Team Member</span><Plus size={16}/></button><button onClick={()=>onEdit({kind:'events'})}><CalendarDays size={17}/><span>Create Event</span><Plus size={16}/></button><button onClick={()=>onEdit({kind:'blog'})}><FileText size={17}/><span>Create Blog</span><Plus size={16}/></button></section><section className="content-summary"><h2>Workspace Content</h2><dl>{content.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section></aside></section>
    <section className="admin-controls panel"><div><h2>Admin Controls</h2><p>Manage staff, feedback, communication, and pending requests.</p></div>{[{title:'Staff & Teachers',text:'Add / remove staff profiles',icon:Users,section:'staff',tone:'blue'},{title:'Reviews',text:'Check parent reviews',icon:Star,section:'reviews',tone:'green'},{title:'Gallery',text:'Add / remove photos',icon:Images,section:'gallery',tone:'coral'},{title:'Pending',text:'Review pending admissions',icon:ClipboardList,section:'admissions',tone:'blue'}].map(item=><button key={item.title} onClick={()=>onNavigate(item.section as Section)}><span><item.icon size={17} className={`control-icon ${item.tone}`}/><strong>{item.title}</strong></span><p>{item.text}</p></button>)}</section>
    <div className="dashboard-note"><span>Admissions, messages, and reviews marked Example are sample records.</span><span>Independent admin workspace</span></div>
  </>;
}
function RecordEditor({editor,onClose,onSave}:{editor:Editor;onClose:()=>void;onSave:(kind:Kind,values:{name:string;status:string;data:Record<string,string>},record?:AdminRecord)=>Promise<AdminRecord>}){
  const {kind,record}=editor,definition=config[kind];
  const [name,setName]=useState(record?.name??''),[status,setStatus]=useState(record?.status??definition.statuses[0]),[values,setValues]=useState<Record<string,string>>(()=>({...Object.fromEntries(definition.fields.map(field=>[field.key,field.type==='date'?today():field.options?.[0]??''])),...record?.data})),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(record?.data.imagePath??''),[saving,setSaving]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(!file)return;const url=URL.createObjectURL(file);setPreview(url);return ()=>URL.revokeObjectURL(url);},[file]);
  function update(key:string,value:string){setValues(prev=>({...prev,[key]:value}));setError('');}
  async function submit(event:FormEvent){event.preventDefault();setError('');setSaving(true);try{
    const data={...values};
    if(file){const response=await fetch('/api/uploads',{method:'POST',headers:{'Content-Type':file.type,'X-File-Name':encodeURIComponent(file.name)},body:file});const result=await response.json() as {error?:string;imagePath:string};if(!response.ok)throw new Error(result.error??'Could not upload the photo.');data.imagePath=result.imagePath;setValues(data);setFile(null);setPreview(result.imagePath);}
    validateRecord(kind,{name,status,data});
    await onSave(kind,{name,status,data},record);toast.success(record?'Changes saved':`${titleCase(definition.singular)} added`);onClose();
  }catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  function renderField(field:Field){const id=`editor-${field.key}`;return <div className={`form-field ${field.type==='textarea'?'full-width':''}`} key={field.key}><label htmlFor={id}>{field.label}{field.required&&<span> *</span>}</label>{field.type==='select'?<Choice id={id} value={values[field.key]??''} options={field.options??[]} onChange={v=>update(field.key,v)} label={field.label}/>:field.type==='textarea'?<Textarea id={id} value={values[field.key]??''} onChange={e=>update(field.key,e.target.value)} required={field.required} maxLength={12000} rows={kind==='blog'&&field.key==='body'?9:4}/>:<Input id={id} type={field.type??'text'} value={values[field.key]??''} onChange={e=>update(field.key,e.target.value)} required={field.required} maxLength={300} min={field.min} max={field.key==='birthDate'?today():field.max} step={field.type==='number'?'1':undefined}/>}</div>;}
  return <Dialog open onOpenChange={open=>{if(!open&&!saving)onClose();}}><DialogContent className="editor-dialog" onInteractOutside={event=>{if(saving)event.preventDefault();}} onEscapeKeyDown={event=>{if(saving)event.preventDefault();}} showCloseButton={!saving}><DialogHeader><DialogTitle>{record?'Edit':'Add'} {definition.singular}</DialogTitle><DialogDescription>{definition.description}</DialogDescription></DialogHeader><form onSubmit={submit} className="editor-form"><div className="form-grid"><div className="form-field full-width"><label htmlFor="record-name">{definition.nameLabel} *</label><Input id="record-name" autoFocus value={name} onChange={e=>{setName(e.target.value);setError('');}} required minLength={2} maxLength={160}/></div>{definition.fields.map(renderField)}<div className="form-field"><label htmlFor="record-status">Status</label><Choice id="record-status" value={status} options={definition.statuses} onChange={setStatus} label="Status"/></div>{(kind==='staff'||kind==='gallery')&&<div className="form-field full-width"><label htmlFor="record-photo">{kind==='gallery'?'Photo *':'Profile photo'}</label><div className="photo-upload">{preview&&<img src={preview} alt="Selected photo preview"/>}<div><Input id="record-photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const selected=e.target.files?.[0]??null;if(selected&&selected.size>8*1024*1024){setError('Choose a photo smaller than 8 MB.');e.target.value='';return;}setFile(selected);setError('');}}/><p>JPEG, PNG, or WebP · up to 8 MB</p></div></div></div>}</div>{record?.data.example==='true'&&<p className="form-example">This is an example record from the design reference.</p>}{error&&<p className="form-error" role="alert">{error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={onClose} disabled={saving}>Cancel</Button><Button type="submit" className="primary-button" disabled={saving}>{saving?'Saving…':record?'Save changes':`Add ${definition.singular}`}</Button></DialogFooter></form></DialogContent></Dialog>;
}
function SettingsForm({data,account,onSaved}:{data:PortalData;account:{username:string;name:string|null};onSaved:(settings:Settings,revision:number)=>void}){
  const [settings,setSettings]=useState(data.settings),[saving,setSaving]=useState(false),[error,setError]=useState('');
  async function submit(event:FormEvent){event.preventDefault();setError('');setSaving(true);try{const valid=settingsSchema.safeParse(settings);if(!valid.success)throw new Error(valid.error.issues[0].message);const result=await requestJson<{settings:Settings;settingsRevision:number}>('/api/settings','PATCH',{settings:valid.data,revision:data.settingsRevision});onSaved(result.settings,result.settingsRevision);toast.success('Settings saved');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  const field=(key:keyof Settings,label:string,type='text')=><div className="form-field" key={key}><label htmlFor={`settings-${key}`}>{label}</label><Input id={`settings-${key}`} type={type} value={settings[key]} onChange={e=>setSettings(prev=>({...prev,[key]:e.target.value}))} maxLength={key==='address'?300:120} required/></div>;
  return <div className="settings-layout"><section className="panel settings-panel"><h2>School Details</h2><form onSubmit={submit}><div className="form-grid">{field('schoolName','School name')}{field('adminName','Admin display name')}{field('email','School email','email')}{field('phone','Phone')}{field('address','Address')}{field('workingDays','Working days')}{field('openTime','Opening time','time')}{field('closeTime','Closing time','time')}</div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="settings-actions"><Button type="submit" className="primary-button" disabled={saving}>{saving?'Saving…':'Save settings'}</Button></div></form></section><aside className="settings-aside"><section className="panel"><ShieldCheck size={27}/><h2>Admin Account</h2><strong>{account.name??data.settings.adminName}</strong><p className="account-email">{account.username}</p><span className="status status-active">Local administrator</span><PasswordForm/></section><section className="settings-connection"><h2>Independent workspace</h2><p>Records and content are saved for this admin panel. The public school website has its own content.</p><p><Clock size={16}/> {data.settings.workingDays}<br/>{timeLabel(data.settings.openTime)} – {timeLabel(data.settings.closeTime)}</p></section></aside></div>;
}
function PasswordForm(){
  const [open,setOpen]=useState(false),[current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
  async function submit(event:FormEvent){event.preventDefault();setError('');if(next!==confirm){setError('New passwords do not match.');return;}setSaving(true);try{await requestJson('/api/auth/password','PATCH',{currentPassword:current,newPassword:next});setOpen(false);setCurrent('');setNext('');setConfirm('');toast.success('Password changed');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  return <><Button className="password-change-button" variant="outline" onClick={()=>setOpen(true)}>Change password</Button><Dialog open={open} onOpenChange={value=>{if(!saving){setOpen(value);setError('');if(!value){setCurrent('');setNext('');setConfirm('');}}}}><DialogContent className="message-dialog"><DialogHeader><DialogTitle>Change admin password</DialogTitle><DialogDescription>Your other signed-in sessions will be logged out.</DialogDescription></DialogHeader><form onSubmit={submit} className="password-change-form"><div className="form-field"><label htmlFor="current-password">Current password</label><Input id="current-password" type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} required maxLength={128}/></div><div className="form-field"><label htmlFor="new-password">New password</label><Input id="new-password" type="password" autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)} required minLength={8} maxLength={128}/></div><div className="form-field"><label htmlFor="confirm-new-password">Confirm new password</label><Input id="confirm-new-password" type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required minLength={8} maxLength={128}/></div>{error&&<p className="form-error" role="alert">{error}</p>}<Button type="submit" className="primary-button" disabled={saving}>{saving?'Saving…':'Change password'}</Button></form></DialogContent></Dialog></>;
}
