export type GalleryItem = { image: string; categories: string[]; alt: string; portrait: boolean };

export const galleryItems: GalleryItem[] = [
  { image: "blog-school-life.jpg", categories: ["Graduation"], alt: "Children at the school graduation celebration", portrait: false },
  { image: "blog-montessori.png", categories: ["Classroom"], alt: "Children displaying their classroom artwork", portrait: false },
  { image: "blog-admissions.png", categories: ["Events"], alt: "Children gathered for a school assembly", portrait: false },
  { image: "blog-parenting.jpg", categories: ["Outdoor"], alt: "Children in outdoor activities (photo 1)", portrait: false },
  { image: "gallery/outdoor-02.jpg", categories: ["Outdoor"], alt: "Children in outdoor activities (photo 2)", portrait: false },
  { image: "gallery/outdoor-03.jpg", categories: ["Outdoor"], alt: "Children in outdoor activities (photo 3)", portrait: true },
  { image: "blog-cultural.jpg", categories: ["Outdoor", "Cultural"], alt: "Children in outdoor activities (photo 4)", portrait: false },
  { image: "gallery/outdoor-05.jpg", categories: ["Outdoor", "Cultural"], alt: "Children in outdoor activities (photo 5)", portrait: false },
  { image: "blog-outdoor.jpg", categories: ["Outdoor"], alt: "Children in outdoor activities (photo 6)", portrait: false },
  { image: "gallery/outdoor-07.jpg", categories: ["Outdoor"], alt: "Children in outdoor activities (photo 7)", portrait: true },
  { image: "gallery/outdoor-08.jpg", categories: ["Outdoor", "Cultural"], alt: "Children in outdoor activities (photo 8)", portrait: false },
  { image: "gallery/outdoor-09.jpg", categories: ["Outdoor"], alt: "Children in outdoor activities (photo 9)", portrait: false },
  { image: "gallery/classroom-01.jpg", categories: ["Classroom"], alt: "Children learning in a classroom (photo 1)", portrait: false },
  { image: "gallery/classroom-02.jpg", categories: ["Classroom"], alt: "Children learning in a classroom (photo 2)", portrait: false },
  { image: "gallery/classroom-03.jpg", categories: ["Classroom"], alt: "Children learning in a classroom (photo 3)", portrait: false },
  { image: "gallery/activities-01.webp", categories: ["Activities", "Events"], alt: "Singing and floating activity (photo 1)", portrait: true },
  { image: "gallery/activities-02.webp", categories: ["Activities", "Events"], alt: "Singing and floating activity (photo 2)", portrait: true },
  { image: "gallery/activities-03.webp", categories: ["Activities", "Events"], alt: "Singing and floating activity (photo 3)", portrait: true },
  { image: "gallery/activities-04.webp", categories: ["Activities", "Events"], alt: "Singing and floating activity (photo 4)", portrait: true },
  { image: "gallery/activities-05.webp", categories: ["Activities", "Events"], alt: "Singing and floating activity (photo 5)", portrait: true },
  { image: "gallery/activities-06.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 6)", portrait: true },
  { image: "gallery/activities-07.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 7)", portrait: true },
  { image: "gallery/activities-08.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 8)", portrait: true },
  { image: "gallery/activities-09.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 9)", portrait: true },
  { image: "gallery/activities-10.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 10)", portrait: true },
  { image: "gallery/activities-11.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 11)", portrait: true },
  { image: "gallery/activities-12.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 12)", portrait: true },
  { image: "gallery/activities-13.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 13)", portrait: false },
  { image: "gallery/activities-14.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 14)", portrait: true },
  { image: "gallery/activities-15.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 15)", portrait: true },
  { image: "gallery/activities-16.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 16)", portrait: true },
  { image: "gallery/activities-17.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 17)", portrait: false },
  { image: "gallery/activities-18.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 18)", portrait: false },
  { image: "gallery/activities-19.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 19)", portrait: true },
  { image: "gallery/activities-20.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 20)", portrait: true },
  { image: "gallery/activities-21.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 21)", portrait: true },
  { image: "gallery/activities-22.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 22)", portrait: true },
  { image: "gallery/activities-23.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 23)", portrait: false },
  { image: "gallery/activities-24.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 24)", portrait: false },
  { image: "gallery/activities-25.jpg", categories: ["Activities"], alt: "Fancy dress competition (photo 25)", portrait: true },
  { image: "gallery/activities-26.jpg", categories: ["Activities"], alt: "Student exhibition (photo 26)", portrait: false },
  { image: "gallery/activities-27.webp", categories: ["Activities", "Events"], alt: "Drawing and coloring activity (photo 27)", portrait: false },
  { image: "gallery/activities-28.webp", categories: ["Activities", "Events"], alt: "Drawing and coloring activity (photo 28)", portrait: false },
  { image: "gallery/activities-29.webp", categories: ["Activities", "Events"], alt: "Drawing and coloring activity (photo 29)", portrait: false },
  { image: "gallery/activities-30.jpg", categories: ["Activities", "Events"], alt: "Drawing and coloring activity (photo 30)", portrait: false },
  { image: "home-hero.webp", categories: ["Activities", "Events"], alt: "Drawing and coloring activity (photo 31)", portrait: false },
  { image: "gallery/activities-32.webp", categories: ["Activities", "Events"], alt: "Drawing and coloring activity (photo 32)", portrait: false },
  { image: "gallery/activities-33.jpg", categories: ["Activities", "Events"], alt: "Drawing and coloring activity (photo 33)", portrait: false },
  { image: "gallery/cultural-01.jpg", categories: ["Cultural"], alt: "School cultural celebration (photo 1)", portrait: false },
  { image: "gallery/cultural-02.jpg", categories: ["Cultural"], alt: "School cultural celebration (photo 2)", portrait: false },
  { image: "gallery/cultural-03.jpg", categories: ["Cultural"], alt: "School cultural celebration (photo 3)", portrait: false },
  { image: "gallery/events-01.jpg", categories: ["Events"], alt: "Saraswati Puja at school (photo 1)", portrait: true },
  { image: "gallery/events-02.jpg", categories: ["Events"], alt: "Saraswati Puja at school (photo 2)", portrait: true },
  { image: "gallery/events-03.webp", categories: ["Events"], alt: "Saraswati Puja at school (photo 3)", portrait: true },
  { image: "gallery/events-04.jpg", categories: ["Events"], alt: "Saraswati Puja at school (photo 4)", portrait: true },
  { image: "gallery/events-05.jpg", categories: ["Events"], alt: "Saraswati Puja at school (photo 5)", portrait: true },
  { image: "gallery/events-06.jpg", categories: ["Events"], alt: "Saraswati Puja at school (photo 6)", portrait: true },
  { image: "gallery/events-07.jpg", categories: ["Events"], alt: "Saraswati Puja at school (photo 7)", portrait: true },
  { image: "gallery/events-08.jpg", categories: ["Events"], alt: "Saraswati Puja at school (photo 8)", portrait: true },
  { image: "gallery/events-09.jpg", categories: ["Events"], alt: "Saraswati Puja at school (photo 9)", portrait: true },
  { image: "gallery/events-10.webp", categories: ["Events"], alt: "Child talent show (photo 10)", portrait: false },
  { image: "gallery/events-11.webp", categories: ["Events"], alt: "Child talent show (photo 11)", portrait: false },
  { image: "gallery/events-12.webp", categories: ["Events"], alt: "Child talent show (photo 12)", portrait: false },
  { image: "gallery/events-13.webp", categories: ["Events"], alt: "Child talent show (photo 13)", portrait: false },
  { image: "gallery/events-14.webp", categories: ["Events"], alt: "Child talent show (photo 14)", portrait: true },
  { image: "gallery/graduation-2081-01.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 1)", portrait: false },
  { image: "gallery/graduation-2081-02.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 2)", portrait: false },
  { image: "gallery/graduation-2081-03.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 3)", portrait: false },
  { image: "gallery/graduation-2081-04.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 4)", portrait: false },
  { image: "gallery/graduation-2081-05.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 5)", portrait: false },
  { image: "gallery/graduation-2081-06.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 6)", portrait: true },
  { image: "gallery/graduation-2081-07.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 7)", portrait: false },
  { image: "gallery/graduation-2081-08.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 8)", portrait: false },
  { image: "gallery/graduation-2081-09.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 9)", portrait: true },
  { image: "gallery/graduation-2081-10.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 10)", portrait: false },
  { image: "gallery/graduation-2081-11.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 11)", portrait: false },
  { image: "gallery/graduation-2081-12.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 12)", portrait: false },
  { image: "gallery/graduation-2081-13.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 13)", portrait: false },
  { image: "gallery/graduation-2081-14.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 14)", portrait: false },
  { image: "gallery/graduation-2081-15.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 15)", portrait: false },
  { image: "gallery/graduation-2081-16.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 16)", portrait: false },
  { image: "gallery/graduation-2081-17.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 17)", portrait: false },
  { image: "gallery/graduation-2081-18.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 18)", portrait: false },
  { image: "gallery/graduation-2081-19.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 19)", portrait: false },
  { image: "gallery/graduation-2081-20.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 20)", portrait: false },
  { image: "gallery/graduation-2081-21.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 21)", portrait: false },
  { image: "gallery/graduation-2081-22.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 22)", portrait: false },
  { image: "gallery/graduation-2081-23.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 23)", portrait: false },
  { image: "gallery/graduation-2081-24.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 24)", portrait: false },
  { image: "gallery/graduation-2081-25.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 25)", portrait: false },
  { image: "gallery/graduation-2081-26.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 26)", portrait: false },
  { image: "gallery/graduation-2081-27.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 27)", portrait: false },
  { image: "gallery/graduation-2081-28.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 28)", portrait: false },
  { image: "gallery/graduation-2081-29.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 29)", portrait: false },
  { image: "gallery/graduation-2081-30.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 30)", portrait: true },
  { image: "gallery/graduation-2081-31.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 31)", portrait: false },
  { image: "gallery/graduation-2081-32.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 32)", portrait: false },
  { image: "gallery/graduation-2081-33.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 33)", portrait: false },
  { image: "gallery/graduation-2081-34.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 34)", portrait: false },
  { image: "gallery/graduation-2081-35.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 35)", portrait: false },
  { image: "gallery/graduation-2081-36.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 36)", portrait: false },
  { image: "gallery/graduation-2081-37.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 37)", portrait: true },
  { image: "gallery/graduation-2081-38.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 38)", portrait: true },
  { image: "gallery/graduation-2081-39.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 39)", portrait: false },
  { image: "gallery/graduation-2081-40.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 40)", portrait: false },
  { image: "gallery/graduation-2081-41.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 41)", portrait: false },
  { image: "gallery/graduation-2081-42.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 42)", portrait: false },
  { image: "gallery/graduation-2081-43.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 43)", portrait: false },
  { image: "gallery/graduation-2081-44.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 44)", portrait: false },
  { image: "gallery/graduation-2081-45.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 45)", portrait: false },
  { image: "gallery/graduation-2081-46.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 46)", portrait: true },
  { image: "gallery/graduation-2081-47.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 47)", portrait: false },
  { image: "gallery/graduation-2081-48.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 48)", portrait: false },
  { image: "gallery/graduation-2081-49.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 49)", portrait: false },
  { image: "gallery/graduation-2081-50.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 50)", portrait: false },
  { image: "gallery/graduation-2081-51.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 51)", portrait: true },
  { image: "gallery/graduation-2081-52.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 52)", portrait: false },
  { image: "gallery/graduation-2081-53.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 53)", portrait: false },
  { image: "gallery/graduation-2081-54.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 54)", portrait: false },
  { image: "gallery/graduation-2081-55.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 55)", portrait: false },
  { image: "gallery/graduation-2081-56.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 56)", portrait: false },
  { image: "gallery/graduation-2081-57.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 57)", portrait: false },
  { image: "gallery/graduation-2081-58.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 58)", portrait: false },
  { image: "gallery/graduation-2081-59.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 59)", portrait: false },
  { image: "gallery/graduation-2081-60.webp", categories: ["Graduation"], alt: "Graduation 2081 celebration (photo 60)", portrait: false },
];
